version: '3'

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql
    deploy:
      placement:
        constraints:
          - node.labels.tag == md
      replicas: 0
    environment:
      MYSQL_ROOT_PASSWORD: rootadmin

  redis:
    image: redis:latest
    ports:
      - 9379:6379
    deploy:
      placement:
        constraints:
          - node.labels.tag == md
      replicas: 1

  mongo:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/data/db
    deploy:
      placement:
        constraints:
          - node.labels.tag == md
      replicas: 1

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    deploy:
      placement:
        constraints:
          - node.labels.tag == md
      replicas: 1

volumes:
 mongodb_data:
 mysql_data:
 mysql_config: