version:  '3.3'

services:
  redis:
    image: redis:latest
    ports:
      - 9379:6379
        mode: host
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1

  mongo:
    image: mongo:latest
    ports:
      - 27018:27017
        mode: host
    volumes:
      - mongodb_data:/data/db
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
        mode: host
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1

volumes:
 mongodb_data: