version: '3.3'
services:
  portainer2:
    image: portainer/portainer
    ports:
      - "9900:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: