version:  '3.4'

services:
  x-config:
    image: ccr.ccs.tencentyun.com/x-cloud/deploy-config:x-config
    ports:
      - 4001:4001
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      replicas: 1

  x-auth:
    image: ccr.ccs.tencentyun.com/x-cloud/deploy-auth:auth
    ports:
      - 3001:3001
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      replicas: 1

  x-upms:
    image: ccr.ccs.tencentyun.com/x-cloud/x-cloud-deploy:x-upms
    ports:
      - 4000:4000
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      replicas: 1

  x-gateway:
    image: ccr.ccs.tencentyun.com/x-cloud/deploy-gateway:x-gateway
    ports:
      - 9999:9999
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      replicas: 1

  x-mc:
    image: ccr.ccs.tencentyun.com/x-cloud/deploy-mc:x-mc
    ports:
      - 4050:4050
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      replicas: 1