version: '3.4'

services:
  x-config:
    image: ccr.ccs.tencentyun.com/x-cloud/deploy-config:x-config
    ports:
      - target: 4001
        published: 4001
        protocol: tcp
        mode: ingress
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      replicas: 1

  x-auth:
    image: ccr.ccs.tencentyun.com/x-cloud/deploy-auth:auth
    ports:
      - target: 3001
        published: 3001
        protocol: tcp
        mode: ingress
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      replicas: 1

  x-upms:
    image: ccr.ccs.tencentyun.com/x-cloud/x-cloud-deploy:x-upms
    ports:
      - target: 4000
        published: 4000
        protocol: tcp
        mode: ingress
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      replicas: 1

  x-gateway:
    image: ccr.ccs.tencentyun.com/x-cloud/deploy-gateway:x-gateway
    ports:
      - target: 9999
        published: 9999
        protocol: tcp
        mode: ingress
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      replicas: 1

  x-mc:
    image: ccr.ccs.tencentyun.com/x-cloud/deploy-mc:x-mc
    ports:
      - target: 4050
        published: 4050
        protocol: tcp
        mode: ingress
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      replicas: 1